name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/**'
    - '*.md'

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_NAME: MapDataPlugin
      DOTNET_VERSION: 9.0.x
      OUT_DIR: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Release
      run: dotnet build ${{ env.PROJECT_NAME }} --no-restore --configuration Release -o ${{ env.OUT_DIR }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}
        path: ${{ env.OUT_DIR }}/*.dll
        if-no-files-found: error
